server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    generate-ddl: true
#spring:datasource:driver-class-name=org.postgresql.Driver